version: '3.8'
services:
  db:
    container_name: store_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: on-failure
    environment:
      - MYSQL_DATABASE=store_db
      - MYSQL_ROOT_PASSWORD=store
    ports:
      - '3306:3306'
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/1.sql